# Generated by Django 4.1.4 on 2023-05-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_price', models.IntegerField()),
                ('book_authour', models.CharField(max_length=200)),
            ],
        ),
    ]
